deployment:
  enabled: true
  type: 'server'
  replicas: 1
  containerPort: 80

application:
  name: todolist

image:
  repository: varunelavia/todo-list
  tag: v1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: http
